// apps/skyrent-demo/src/components/RestartDemoFlow.tsx
import { useRestartDemoFlow } from "../hooks/useRestartDemoFlow";

type Props = {
  /** Runs before cart/verification clear (e.g. reset page-local state on Browse). */
  onBeforeRestart?: () => void;
};

export function RestartDemoFlow({ onBeforeRestart }: Props) {
  const restart = useRestartDemoFlow();

  return (
    <div className="demo-restart-footer">
      <button
        type="button"
        className="demo-restart"
        onClick={() => {
          onBeforeRestart?.();
          restart();
        }}
      >
        Leave and start over
      </button>
    </div>
  );
}

// apps/skyrent-demo-vue/src/components/RestartDemoFlow.vue
<template>
  <div class="demo-restart-footer">
    <button
      type="button"
      class="demo-restart"
      @click="handleRestart"
    >
      Leave and start over
    </button>
  </div>
</template>

<script setup lang="ts">
import { useRestartDemoFlow } from "../hooks/useRestartDemoFlow";

const props = defineProps<{
  onBeforeRestart?: () => void;
}>();

const restart = useRestartDemoFlow();

function handleRestart() {
  props.onBeforeRestart?.();
  restart();
}
</script>
